import { expect, test } from "@playwright/test";

test("canvas grows right and down, keeps its origin and does not shrink after moving back", async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 1000 });
  await page.goto("http://localhost:1420");
  await page.getByRole("button", { name: "만들기", exact: true }).click();
  const viewport = page.locator(".flow-canvas-scroll");
  const canvas = page.locator(".graph-canvas");
  await viewport.hover({ position: { x: 250, y: 200 } });
  await page.keyboard.press("Control+t");
  const original = await canvas.evaluate(el => ({ width: el.clientWidth, height: el.clientHeight }));
  const node = page.locator(".flow-node");
  const box = (await node.boundingBox())!;
  const view = (await viewport.boundingBox())!;
  await page.mouse.move(box.x + 30, box.y + 30);
  await page.mouse.down();
  await page.mouse.move(view.x + view.width - 80, view.y + view.height - 80, { steps: 10 });
  await page.mouse.up();
  const grown = await canvas.evaluate(el => ({ width: el.clientWidth, height: el.clientHeight }));
  expect(grown.width).toBeGreaterThan(original.width);
  expect(grown.height).toBeGreaterThan(original.height);
  const moved = (await node.boundingBox())!;
  await page.mouse.move(moved.x + 30, moved.y + 30);
  await page.mouse.down();
  await page.mouse.move(view.x + 1, view.y + 1, { steps: 10 });
  await page.mouse.up();
  expect(await canvas.evaluate(el => ({ width: el.clientWidth, height: el.clientHeight }))).toEqual(grown);
  expect(await page.locator(".graph-node-wrap").evaluate(el => ({ x: parseFloat((el as HTMLElement).style.left), y: parseFloat((el as HTMLElement).style.top) }))).toEqual({ x: 0, y: 0 });
  expect(await canvas.evaluate(el => ({ left: (el as HTMLElement).style.left, top: (el as HTMLElement).style.top, origin: getComputedStyle(el).transformOrigin }))).toMatchObject({ origin: "0px 0px" });
});

test("Ctrl+wheel zoom keeps world geometry and scales creation, movement, resize and selection correctly", async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 1000 });
  await page.goto("http://localhost:1420");
  await page.getByRole("button", { name: "만들기", exact: true }).click();
  const viewport = page.locator(".flow-canvas-scroll");
  await viewport.hover({ position: { x: 400, y: 250 } });
  await page.keyboard.press("Control+t");
  const node = page.locator(".flow-node").first();
  const wrap = page.locator(".graph-node-wrap").first();
  const originalStyle = await wrap.getAttribute("style");
  const original = (await node.boundingBox())!;
  await page.keyboard.down("Control");
  await page.mouse.wheel(0, Math.log(2) / 0.002);
  await page.keyboard.up("Control");
  await expect(page.getByLabel("캔버스 배율")).toContainText("50%");
  expect(await wrap.getAttribute("style")).toBe(originalStyle);
  const scaled = (await node.boundingBox())!;
  expect(scaled.width).toBeCloseTo(original.width / 2, 0);
  expect(scaled.height).toBeCloseTo(original.height / 2, 0);
  await page.mouse.move(scaled.x + 20, scaled.y + 20);
  await page.mouse.down();
  await page.mouse.move(scaled.x + 100, scaled.y + 60, { steps: 5 });
  await page.mouse.up();
  const moved = (await node.boundingBox())!;
  expect(moved.x - scaled.x).toBeCloseTo(80, 0);
  expect(moved.y - scaled.y).toBeCloseTo(40, 0);
  await node.hover();
  const handle = (await page.getByRole("button", { name: "se 모서리 크기 조절" }).boundingBox())!;
  await page.mouse.move(handle.x + handle.width / 2, handle.y + handle.height / 2);
  await page.mouse.down();
  await page.mouse.move(handle.x + handle.width / 2 + 40, handle.y + handle.height / 2 + 30, { steps: 5 });
  await page.mouse.up();
  const resized = (await node.boundingBox())!;
  expect(resized.width - moved.width).toBeCloseTo(40, 0);
  expect(resized.height - moved.height).toBeCloseTo(30, 0);
  await viewport.hover({ position: { x: 800, y: 350 } });
  await page.keyboard.press("Control+t");
  await expect(page.locator(".flow-node")).toHaveCount(2);
  const second = (await page.locator(".flow-node").nth(1).boundingBox())!;
  const view = (await viewport.boundingBox())!;
  expect(second.x + second.width / 2).toBeCloseTo(view.x + 800, 0);
  await page.mouse.move(resized.x - 10, resized.y - 10);
  await page.mouse.down();
  await page.mouse.move(second.x + second.width + 10, second.y + second.height + 10, { steps: 5 });
  await page.mouse.up();
  await expect(page.locator(".flow-node.is-selected")).toHaveCount(2);
  await page.keyboard.down("Control");
  await page.mouse.wheel(0, -Math.log(2) / 0.002);
  await page.keyboard.up("Control");
  await expect(page.getByLabel("캔버스 배율")).toContainText("100%");
  await viewport.evaluate(el => { el.scrollLeft = 200; el.scrollTop = 100; });
  await viewport.hover({ position: { x: 500, y: 300 } });
  const before = await viewport.evaluate(el => ({ x: el.scrollLeft + 500, y: el.scrollTop + 300 }));
  await page.keyboard.down("Control");
  await page.mouse.wheel(0, -200);
  await page.keyboard.up("Control");
  await expect(page.getByLabel("캔버스 배율")).toContainText("149%");
  const after = await viewport.evaluate(el => ({ x: (el.scrollLeft + 500) / Math.exp(0.4), y: (el.scrollTop + 300) / Math.exp(0.4) }));
  expect(Math.abs(after.x - before.x)).toBeLessThan(1);
  expect(Math.abs(after.y - before.y)).toBeLessThan(1);
});
